### ISSUE TITLE
Cannot finish connection handshake on Evmos v6.0.1 due to consensus height checks

### ISSUE THREAD

**Issue by litvinsky** [informalsystems/ibc-rs#2433]
## Summary of Bug
Can not create new IBC (Hermes) between _EVMOS release v6.0.x_ with _cosmos/previous evmos release versions_
- cosmos v7.0.2 ❌ ⇌ evmos v6.0.1
- evmos v5.0.0 ❌ ⇌ evmos v6.0.1
- evmos v4.0.1 ❌ ⇌ evmos v6.0.1

✅  No issue if:
- cosmos v7.0.2 ⇌ evmos v5.0.0 & v4.0.1
- evmos ⇌ evmos (same version)
- evmos v4.0.1 ⇌ evmos v5.0.0

## Version
**v0.15.0**

## Steps to Reproduce
- Setup [gaia v7.0.2](https://github.com/cosmos/gaia/tree/v7.0.2)
- Setup [evmos v6.0.1](https://github.com/evmos/evmos/tree/v6.0.1)
- Setup Hermes to connect those chains
- Create tendermint light client, both ok
- Create connection, both ok
- You will face error in `hermes -c ... tx raw conn-ack ...` step

## Screenshots
https://imgur.com/a/JoJILpl

In case image dead:

> 2022-07-18T07:04:34.127628Z  WARN ThreadId(01) [cosmos-8 -> evmos_9007-1:07-tendermint-0] resolving trusted height from the full list of consensus state heights for target height 8-11; this may take a while
> 2022-07-18T07:04:34.154119Z  INFO ThreadId(06) wait_for_block_commits: waiting for commit of tx hashes(s) 2824142295B2239B69EE85E536AC1EFF31D43E4679CEF803C5A18922D8AEB083 id=evmos_9007-1
> 2022-07-18T07:04:36.415496Z ERROR ThreadId(11) send_tx_with_account_sequence_retry{id=cosmos-8}:estimate_gas: failed to simulate tx. propagating error to caller: gRPC call failed with status: status: Unknown, message: "failed to execute message; message index: 1: connection handshake open ack failed: consensus height is greater than or equal to the current block height (8-11 >= 8-11): invalid height", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "x-cosmos-block-height": "11"} }
> Error: connection error: failed during a transaction submission step to chain 'cosmos-8': gRPC call failed with status: status: Unknown, message: "failed to execute message; message index: 1: connection handshake open ack failed: consensus height is greater than or equal to the current block height (8-11 >= 8-11): invalid height", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "x-cosmos-block-height": "11"} }
> ERR: Operation failed (tx raw conn-ack)

## Additional context
This is local test, I didn't do any proposal to upgrade, I just remove old chains and create new chains, new IBC. Everything are fresh

The following files I backup for reference purpose
- [Genesis of chain 1](https://github.com/litvinsky/EVMOS-sample-scripts/blob/v6.0.1-bug-report/bug-report/cosmos-8-genesis.json)
- [Genesis of chain 2](https://github.com/litvinsky/EVMOS-sample-scripts/blob/v6.0.1-bug-report/bug-report/evmos_9007-1-genesis.json)
- [Hermes config.toml](https://github.com/litvinsky/EVMOS-sample-scripts/blob/v6.0.1-bug-report/bug-report/hermes-config.toml)

P/s: If you need an test environment which can create 2 chains & IBC really fast in few minutes, prepare an Ubuntu machine and dm me in Slack, I will guide you

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ancazamfir** [comment]
Have you changed the block time in evmos v6.0.1? There are a few failures we notice more often when block times are significantly different between the two chains. They are typically related to the client consensus state height and timestamp that appear "in the future". 
In particular, for the one you see it is this [try check](https://github.com/cosmos/ibc-go/blob/aaccbd193f19f97f8068278141044bf324e6425c/modules/core/03-connection/keeper/handshake.go#L79 ) and the [ack check](https://github.com/cosmos/ibc-go/blob/aaccbd193f19f97f8068278141044bf324e6425c/modules/core/03-connection/keeper/handshake.go#L169 ) in the on-chain handlers. It is not clear to me why the check is for `>=` and not `>`.  I opened https://github.com/cosmos/ibc-go/issues/1732 to clarify. But we might need to add a check in hermes and wait for the "slow" chain to advance one height before we try the simulation.

In the meantime so you can make some progress, I see that you are using the `tx raw` commands which are really meant for testing. You may have a better chance with [`hermes create connection`](https://hermes.informal.systems/commands/path-setup/connections.html#establish-connection) which will most likely see the same error but has a build in retry mechanism. Or just repeat the tx raw command.

**Comment by litvinsky** [comment]
Thanks @ancazamfir! The problem was solved with `hermes create connection` command!

**Comment by ancazamfir** [comment]
I will reopen this temporarily until we decide how to fix it long term (ibc-go or hermes). The `hermes create connection` may still fail in extreme cases with exhausted retries.
